<?php

namespace AppBundle\Repository;

/**
 * BigDaddyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BigDaddyRepository extends \Doctrine\ORM\EntityRepository
{
}
