<?php

namespace AppBundle\Repository;

/**
 * DaddyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaddyRepository extends \Doctrine\ORM\EntityRepository
{
}
