<?php

namespace AppBundle\Repository;

/**
 * SpeedDaddyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeedDaddyRepository extends \Doctrine\ORM\EntityRepository
{
}
